import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";

import { Inter } from "next/font/google";
import "./globals.css";
import Office from "./babylon/Office";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={GeistSans.className}>
      <body className="h-screen w-screen">
        <Office />
        {children}
      </body>
    </html>
  );
}
